apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: prometheus
    targetRevision: 25.3.1
    helm:
      valuesObject:
        pushgateway:
          enabled: false
        # Okta group to grafana role mapping. Every non-mapped group is Viewer
        roleMapping:
        - group: platform-engineering-element
          role: Admin
        - group: engineering-function
          role: Editor
        - group: information-security-function
          role: Editor
        - group: product-function
          role: Viewer
        - group: business-operations-market-operations-functional-team
          role: Viewer
        # Based on https://github.com/grafana/helm-charts/tree/main/charts/grafana
        replicas: 1
        podDisruptionBudget:
          maxUnavailable: 1
        ingress:
          enabled: true
          hosts:
          - grafana.internal.corp.traderepublic.com
          ingressClassName: nginx-internal
          tls:
          - hosts:
            - grafana.internal.corp.traderepublic.com
            secretName: wildcard.internal.corp.traderepublic.com-tls
        initChownData:
          enabled: false
        autoscaling:
          enabled: true
          minReplicas: 2
          maxReplicas: 5
          targetCPU: "60"
        sidecar:
          dashboards:
            enabled: true
            searchNamespace: ALL
            folderAnnotation: "grafana_dashboard_folder"
            provider:
              foldersFromFilesStructure: true
        serviceMonitor:
          enabled: true
        grafana.ini:
          users:
            viewers_can_edit: true
            editors_can_admin: true
          auth:
            disable_login_form: false
          auth.okta:
            enabled: true
            name: Okta
            icon: okta
            allow_signup: false
            client_id: 0oa7zpw95tG8rlDLW417
            scopes: openid profile email groups
            auth_url: https://traderepublic.okta.com/oauth2/v1/authorize
            token_url: https://traderepublic.okta.com/oauth2/v1/token
            api_url: https://traderepublic.okta.com/oauth2/v1/userinfo
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
